export const enLocale = {
    feelsLike: 'feels like',
    wind: 'wind',
    ms: 'm/s',
    humidity: 'humidity',
    searchCity: 'Search city or ZIP',
    search: 'search',
    latitude: 'Latitude',
    longitude: 'Longitude',
    days: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    months: [
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December',
    ],
};
